# /docs/_config.yml
title: Society of Unified Life
baseurl: "/docs" # leave blank if hosted at root
markdown: kramdown
theme: pages-themes/tactile@v0.2.0 # optional
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

